codecov:
    bot: "codecov-io"
    ci:
        - "circleci"
    strict_yaml_branch: "master"
    max_report_age: 24
    disable_default_path_fixes: no
    require_ci_to_pass: yes
    notify:
        wait_for_ci: yes
