scopes:
    "/GET/users":
        - "users:read"
        - "users:write"
    "/GET/users/*":
        - "users:read"
        - "users:write"
    "/POST/users":
        - "users:write"
    "/PUT/users":
        - "users:write"
    "/DELETE/users/*":
        - "users:write"
    "/OPTIONS/users":
        - "users:read"
        - "users:write"
    "/OPTIONS/users/*":
        - "users:read"
        - "users:write"
    "/POST/users/password":
        - "users:write"
    "/POST/users/password/reset/*":
        - "users:write"
    "/GET/blogs":
        - "pages:read"
        - "pages:write"
    "/POST/blogs":
        - "pages:write"
    "/GET/pages":
        - "pages:read"
        - "pages:write"
    "/POST/pages":
        - "pages:write"
    "/PUT/pages":
        - "pages:write"
    "/GET/pages/*":
        - "pages:read"
        - "pages:write"
    "/DELETE/pages/*":
        - "pages:write"
    "/POST/pages/*/activate":
        - "pages:write"
    "/POST/pages/*/deactivate":
        - "pages:write"
    "/GET/settings":
        - "settings:read"
        - "settings:write"
    "/GET/settings/*":
        - "settings:read"
        - "settings:write"
    "/PUT/settings":
        - "settings:write"

scope_policies:
    "users:read":
        - "/GET/users"
        - "/GET/users/*"
    "users:write":
        - "/GET/users"
        - "/GET/users/*"
        - "/POST/users"
        - "/PUT/users"
        - "/DELETE/users/*"
        - "/POST/users/password"
        - "/POST/users/password/reset/*"
    "pages:read":
        - "/GET/pages"
        - "/GET/blogs"
        - "/GET/pages/*"
    "pages:write":
        - "/GET/pages"
        - "/GET/blogs"
        - "/POST/blogs"
        - "/GET/pages/*"
        - "/POST/pages"
        - "/PUT/pages"
        - "/DELETE/pages/*"
        - "/POST/pages/*/activate"
        - "/POST/pages/*/deactivate"
    "settings:read":
        - "/GET/settings"
        - "/GET/settings/*"
    "settings:write":
        - "/GET/settings"
        - "/GET/settings/*"
        - "/PUT/settings"
