scopes:
    "/GET/users":
        - "users:read"
        - "users:write"
    "/GET/users/*":
        - "users:read"
        - "users:write"
    "/POST/users":
        - "users:write"
    "/PUT/users/*":
        - "users:write"
    "/DELETE/users/*":
        - "users:write"
    "/OPTIONS/users":
        - "users:read"
        - "users:write"
    "/OPTIONS/users/*":
        - "users:read"
        - "users:write"
    "/POST/users/password":
        - "users:write"
    "/POST/users/password/reset/*":
        - "users:write"

scope_policies:
    "users:read":
        - "/GET/users"
        - "/GET/users/*"
    "users:write":
        - "/GET/users"
        - "/GET/users/*"
        - "/POST/users"
        - "/PUT/users/*"
        - "/DELETE/users/*"
        - "/POST/users/password"
        - "/POST/users/password/reset/*"
    "users:default":
        - "/GET/users/{{user_id}}"
        - "/POST/users/password"
        - "/POST/users/password/reset/{{user_id}}"
        - "/PUT/users/{{user_id}}"
        - "/DELETE/users/{{user_id}}"
