version: 2
jobs:
    build:
        docker:
            - image: circleci/golang:1.12.9-node-browsers-legacy
            - image: circleci/mysql:8.0.20-ram
              command: --default-authentication-plugin=mysql_native_password
              environment:
                  MYSQL_ROOT_PASSWORD: password
                  MYSQL_DATABASE: distro-blog-test

        working_directory: /go/src/github.com/reecerussell/distro-blog

        steps:
            - checkout

            - run:
                  name: Waiting for MySQL to be ready
                  command: |
                      sleep 15; echo Done.

            - run:
                  name: Install MySQL CLI
                  command: |
                      sudo apt install -y default-mysql-client --fix-missing
                      mysql -h 127.0.0.1 -u root -ppassword distro-blog-test < test/test-db-setup.sql

            # Install Go dependencies.
            - run: go get github.com/google/uuid
            - run: go get github.com/go-sql-driver/mysql
            - run: go get golang.org/x/crypto/pbkdf2
            - run: go get github.com/aws/aws-lambda-go/events
            - run: go get github.com/aws/aws-lambda-go/lambda

            # Tests
            - run:
                  name: Run unit tests
                  environment:
                      CONN_STRING: root:password@tcp(127.0.0.1)/distro-blog-test?parseTime=true
                  command: go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic
            - run: bash <(curl -s https://codecov.io/bash)

            - store_artifacts:
                  path: coverage.txt

workflows:
    version: 2
    build-test:
        jobs:
            - build
