version: 2
jobs:
    build:
        docker:
            - image: circleci/mysql
              environment:
                  MYSQL_ROOT_PASSWORD: password
                  MYSQL_DATABASE: distro-blog-test
            - image: circleci/golang

        steps:
            - checkout
            - run:
                  name: Waiting for MySQL to be ready
                  command: |
                      apt-get update
                      apt-get install netcat
                      for i in `seq 1 30`;
                      do
                      nc -z 127.0.0.1 3306 && echo Success && exit 0
                      echo -n .
                      sleep 1
                      done
                      echo Failed waiting for MySQL && exit 1

            - run:
                  name: Install MySQL CLI
                  command: |
                      sudo apt-get install mysql-client
                      mysql -h 127.0.0.1 -u root -ppassword distro-blog-test < test/test-db-setup.MySQL

            # Install Go dependencies.
            - run: go get github.com/google/uuid
            - run: go get github.com/go-sql-driver/mysql
            - run: go golang.org/x/crypto/pbkdf2

            # Tests
            - run:
                  name: Run unit tests
                  environment:
                      CONN_STRING: root:password@tcp(db)/distro-blog-test?parseTime=true
                  command: |
                      go test -v ./...

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
