version: 2
jobs:
    build:
        docker:
            - image: circleci/golang
            - image: circleci/mysql
              command: --default-authentication-plugin=mysql_native_password
              environment:
                  MYSQL_ROOT_PASSWORD: password
                  MYSQL_DATABASE: distro-blog-test

        working_directory: /go/src/github.com/reecerussell/distro-blog

        steps:
            - checkout
            
            - restore_cache:
                keys:
                    - v1-pkg-cache
            
            - run:
                  name: Waiting for MySQL to be ready
                  command: |
                      sleep 30; echo Done.

            - run:
                  name: Install MySQL CLI
                  command: |
                      sudo apt install -y mariadb-client
                      mysql -h 127.0.0.1 -u root -ppassword distro-blog-test < test/test-db-setup.sql

            # Install Go dependencies.
            - run: go get github.com/google/uuid
            - run: go get github.com/go-sql-driver/mysql
            - run: go get golang.org/x/crypto/pbkdf2

            # Tests
            - run:
                  name: Run unit tests
                  environment:
                      CONN_STRING: root:password@tcp(127.0.0.1)/distro-blog-test?parseTime=true
                  command: go test -v ./...
                  
            - run: make
            - save_cache:
                key: v1-pkg-cache
                paths:
                    - "/go/pkg"
                    
workflows:
    version: 2
    build-test:
        jobs:
            - build
